### PR TITLE
Update to Angular 2.0.0-alpha.31...Swapped out fetch with Http. Also updated typings to be easier to work with and update

### PR DESCRIPTION
**Pull request by NathanWalker**
Because it's nice to be on the bleeding edge.

### CODE REVIEW

**Comment by PatrickJS** [comment]
such bleeding

**Comment by lBilali** [comment]
@NathanWalker Did you test if everything works with 2.0.0-alpha.31?

RouterOutlet is changed by commit https://github.com/angular/angular/commit/a9a552c112da1397a0122acdbecbd52bc88e1906 renaming activate method to commit, so LoggedInRouterOutlet  does not work (every route can be accessed without a jwt).

**Comment by NathanWalker** [comment]
If you could help update the changes for RouterOutlet would be appreciated. :)

**Comment by lBilali** [comment]
I tried last night but failed on overriding commit method. somehow it complained that super does not have commit method.
you can try by changing activate method with the one below. Maybe you will have better luck :)

commit(instruction) {
    var url = this._parentRouter.lastNavigationAttempt;
    if (!this.publicRoutes[url] && !localStorage.getItem('jwt')) {
      instruction.component = Login;
    }
    return super.commit(instruction);
  }

For more I was thinking maybe authentication can be implemented differently with the newly introduced hooks.

P.S. I'm not in front of my computer to make a proper pull request

**Comment by lBilali** [comment]
Making the change should work. The complain I got is because of the typings which is on alpha-26 :(

**Comment by NathanWalker** [comment]
Thanks for trying I'll see what I can do.
The typings thing is one gripe I have with TypeScript and Angular 2 right now. It seems every sample project out there right now has different ways of including or referencing typings and/or different sets with different names. There should be one and only one way to include and update the typings to avoid this confusion.

**Comment by NathanWalker** [comment]
So it is related to type definitions, of which, I don't see alpha.31 posted here yet:
https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2

I cannot find type definitions on angular's repo either. I find this confusing. It seems that when they make api changes, new typings would be generated in their source to reflect those api changes?

At this point, I believe we need to wait until alpha.31 shows up on DefinitelyTyped repo... ?

**Comment by NathanWalker** [comment]
Typings have now been updated on this PR to follow a suggestion by @gdi2290 for the https://github.com/angular-class/angular2-webpack-starter repo... which is very smart. It allows easy updating of the tsd installed typings and management of custom typings without them intermingling. :+1: 

Everything appears to work as intended with the exception of one TypeScript Warning I still see in the output:

```
WARNING in ./src/app/LoggedInOutlet.ts
(13,7): Supplied parameters do not match any signature of call target.
```

... because the latest router.d.ts typings do not include the `RouterOutlet` `constructor` signature. 
Investigating a clean way to extend distributed/installed typings with custom modifications to deal with this.

**Comment by NathanWalker** [comment]
Reason for this warning
```
WARNING in ./src/app/LoggedInOutlet.ts
(13,7): Supplied parameters do not match any signature of call target.
```
... is because the latest router.d.ts typings do not include the `RouterOutlet` `constructor` signature. 
Investigating a clean way to extend distributed/installed typings with custom modifications to deal with this.

**Comment by NathanWalker** [comment]
Extending existing TypeScript definitions is something that has currently been proposed but is not yet supported for classes:

https://github.com/Microsoft/TypeScript/issues/819

If you agree, as I do, that this should be supported in TypeScript, add a +1 there. :+1:

**Comment by NathanWalker** [comment]
I've added this issue to see if the RouterOutlet constructor signature could be included in the generated type definitions to solve this (cleanly)...
https://github.com/angular/angular/issues/3291

**Comment by ctindel** [comment]
@NathanWalker : 

I updated my code to match what was in the PR.  For some reason now I am getting an alert window popping up saying "response.json is not a function" when I try to login.

I'm also getting a warning message saying "./app/LoggedInOutlet.ts
(13,7): Supplied parameters do not match any signature of call target. (2346)"

This is regarding the call to:
super(_elementRef, _loader, _parentRouter, nameAttr);

Any ideas?  Are you seeing these on your side?

**Comment by NathanWalker** [comment]
@ctindel I have seen the typescript warning around LoggedInOutlet due to fact that the router.d.ts file is not accurate and they are working on correcting that here:
https://github.com/angular/angular/issues/3282
It needs to include the construction signature.
I haven't seen the response.json error and will have a look next time I get a chance.

Hopefully the router typings will be updated on DefinitelyTyped soon.

**Comment by ctindel** [comment]
@NathanWalker 

It has something to do with the new http.post call.  I switched my code back to window.fetch and it works fine.

Is there documentation anywhere describing how to use window.post?  I don't see any examples online written like yours with the .map(status), .map(json), etc.  I saw one example using .map(res => res.json()) but then nothing after that.

**Comment by NathanWalker** [comment]
n/a

**Pull request closed without merging**
