### PR TITLE
Upgraded to alpha 29

### PR DESCRIPTION
**Pull request by vcardins**
Hi, still having issue with LoggedInRouterOutlet. I had to extend from routerMod.RouterOutlet once directly to RouterOutlet didn't work same for the activate method. 
Another strange issue is the view, it is showing duplicated (http://screencast.com/t/j7XLRbzeXU).
I'll keep looking on that, sent the PR quickly in case you can figure it out sooner.
Thanks !

### CODE REVIEW

**Comment by mgonto** [comment]
It's repated beacuse you're importing both the LoggedInRouterOutlet as well as the RouterOutlet in the app.ts. Remove the RouterOutlet and that should work.

Regarding the extend no idea why it doesn't work. hmm.

**Comment by vcardins** [comment]
Actually it was not exactly that, just updated the PR. No luck yet with the LoggedInRouterOutlet activate method.

``` javascript
if (uri === '' || uri === '/') {
      router.navigate('/home');
 } else {
      //router.navigate(uri); This line is causing the repetition. Any thoughts?
 }
```

**Comment by PatrickJS** [comment]
I have a working version here https://github.com/auth0/angular2-authentication-sample/pull/24

**Comment by PatrickJS** [comment]
this can be closed

**Pull request closed without merging**
