### PR TITLE
Update to Angular 2.0.0-alpha.30

### PR DESCRIPTION
**Pull request by NathanWalker**

### CODE REVIEW

**Comment by mgonto** [comment]
Thanks :).

**Comment by PatrickJS** [comment]
you can replace `fetch` with `Http` now that the headers work

**Comment by mgonto** [comment]
Yep. I will. Thanks @gdi2290

**Comment by PatrickJS** [comment]
for example

``` es6
    window.fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': 'bearer ' + this.jwt
      }
    })
    .then(status)
    .then(text)
    .then((response) => {
      this.response = response;
    })
    .catch((error) => {
      this.response = error.message;
    });
```

``` typescript
    http.get(url, {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': 'bearer ' + this.jwt
      }
    })
    .toRx()
    .map(status)
    .map(text)
    .subscribe(
      response => {
        this.response = response;
      },
      error => {
        this.response = error.message;
      }
    )
```

**Comment by NathanWalker** [comment]
Oh thanks @ctindel, I think we do need to do that right @mgonto?

**Comment by mgonto** [comment]
Yep we do :).

**Pull request merged**
